### ISSUE TITLE
There are no such field in recieved json as mappedActionV2

### ISSUE THREAD

**Issue by freeseacher** [opsgenie/oec-scripts#1]
While launching OEC integration i got that like json
```json
{
  "action": "Create",
  "alert": {
    "actions": [
      "Create Jira Issue",
      "Restart",
      "AnExampleAction"
    ],
    "addedTags": "OverwriteQuietHours,Critical",
    "alertId": "370fe347-849a-4418-83fc-1557f7a11652-1554384340747",
    "alias": "370fe347-849a-4418-83fc-1557f7a11652-1554384340747",
    "createdAt": 1554384340747,
    "entity": "An example entity",
    "message": "TESTALERT",
    "priority": "P5",
    "recipients": [],
    "source": "XXX",
    "tags": [
      "OverwriteQuietHours",
      "Critical"
    ],
    "teams": [],
    "tinyId": "8861",
    "updatedAt": 1554384341542000000,
    "username": "Alert API"
  },
  "alertId": "370fe347-849a-4418-83fc-1557f7a11652-1554384340747",
  "customerId": "XXXX",
  "integrationId": "d3752135-3a42-4c3e-96c0-435e59bf1b24",
  "integrationName": "OEC-XX",
  "integrationType": "OEC",
  "mappedActionDto": {
    "extraField": "",
    "mappedAction": "postActionToOEC"
  },
  "params": {
    "action": "Create",
    "alert": {
      "actions": [
        "Create Jira Issue",
        "Restart",
        "AnExampleAction"
      ],
      "addedTags": "OverwriteQuietHours,Critical",
      "alertId": "370fe347-849a-4418-83fc-1557f7a11652-1554384340747",
      "alias": "370fe347-849a-4418-83fc-1557f7a11652-1554384340747",
      "createdAt": 1554384340747,
      "entity": "An example entity",
      "message": "TESTALERT",
      "priority": "P5",
      "recipients": [],
      "source": "XXX",
      "tags": [
        "OverwriteQuietHours",
        "Critical"
      ],
      "teams": [],
      "tinyId": "8861",
      "updatedAt": 1554384341542000000,
      "username": "Alert API"
    },
    "alertId": "370fe347-849a-4418-83fc-1557f7a11652-1554384340747",
    "customerId": "XXXX",
    "integrationId": "d3752135-3a42-4c3e-96c0-435e59bf1b24",
    "integrationName": "OEC-XX",
    "integrationType": "OEC",
    "mappedActionDto": {
      "extraField": "",
      "mappedAction": "postActionToOEC"
    },
    "sendViaMarid": false,
    "source": {
      "name": "XXX",
      "type": "API"
    },
    "type": "oec"
  },
  "sendViaMarid": false,
  "source": {
    "name": "XXX",
    "type": "API"
  },
  "type": "oec"
}
```
as far as i can see there are no such field as referenced in https://github.com/opsgenie/oec-scripts/blob/master/Jira/jiraActionExecutor.py#L77
Am i am have right configuration in oec on opsgenie side ?

**Comment by metehanozturk** [comment]
OEC integration payload does not contain mappedActionV2 because mapped actions is fixed as "postActionToOEC". Jira integration payload with "Send Via OEC" option (beta feature for now), just like Marid, contains and this script is designed for this case. Mapped action name is not meaningful for OEC integration itself. You should use Jira integration to achieve this field or modify the script. For the second case, you can add a new flag to the configuration file for each different mapped action and parse it in the script.

You can access customer support to activate the beta feature to use Jira integration with "Send Via OEC" option.

**Comment by freeseacher** [comment]
yep. tnx. all ready got beta features enabled just not double check jira integration for additional fields.

**Comment by freeseacher** [comment]
OEC Integration with "Send Via OEC" has the same flaw as  "Send Via Marid" and direct Jira Integration. They all mimic the same json and send simplified json without any details. 
So i have to discard that option and only use direct integration to fill custom fields in jira.

**Comment by metehanozturk** [comment]
If I did not get misunderstand, you don't want to use the simplified version of json and use OEC integration instead of Jira integration to get more detailed info about the alert. Jira integration sends only necessary alert info to Jira or OEC. If do you think that there is a lack of info, there is a chance to get all alert payload by using Integration API of Opsgenie. You can send a get alert request with the help of alertId. 
Other chance is that using OEC integration and modify the script according to it.

**Comment by freeseacher** [comment]
In my opinion additional GET in script looks like an ugly solution. I have to provide two set of credentials. one for jira integration another one for that GET request. 
My script have to support additional logic for responses of opsgenie, respond to 429, 500 and other. To much additional pain on pretty straight task.

**Comment by metehanozturk** [comment]
This is a valid alternative solution for now. Jira integration does not support additional fields. On the other hand, alertId and apikey are already provided at both case, so at least you don't want to support additional credentials to GET alert details to send a request to Alert API. If you use Jira integration, Jira username and password are also supported.

Alternatives are those for now but the issue will be definitely evaluated to add custom fields.

**Comment by freeseacher** [comment]
yep. tnx. jira as you probably know is all about integration and custom fields is a key to make it great.
